package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"

	"github.com/hueristiq/hqgolog"
	"github.com/spf13/pflag"
)

var (
	path string

	schemesTmpl = template.Must(template.New("schemes").Parse(`// This file is autogenerated. Please do not edit manually.

package schemes

// Schemes is a sorted list of all IANA assigned schemes.
// Source: https://www.iana.org/assignments/uri-schemes/uri-schemes-1.csv
var Schemes = []string{
{{range $scheme := .Schemes}}` + "\t`" + `{{$scheme}}` + "`" + `,
{{end}}}
`))
)

func init() {
	pflag.StringVarP(&path, "path", "p", "", "")

	pflag.CommandLine.SortFlags = false
	pflag.Usage = func() {
		h := "USAGE:\n"
		h += "  schemesgen [OPTIONS]\n"

		h += "\nOPTIONS:\n"
		h += " -p, --path string                 output path\n"

		fmt.Fprintln(os.Stderr, h)
	}

	pflag.Parse()
}

func main() {
	hqgolog.Info().Msgf("Generating %s...", path)

	schemes := getSchemesList()

	if err := writeSchemes(schemes, path); err != nil {
		hqgolog.Fatal().Msg(err.Error())
	}
}

func getSchemesList() (schemes []string) {
	schemesSourcesURL := "https://www.iana.org/assignments/uri-schemes/uri-schemes-1.csv"

	resp, err := http.Get(schemesSourcesURL)
	if err != nil {
		hqgolog.Fatal().Msg(err.Error())
	}

	defer resp.Body.Close()

	r := csv.NewReader(resp.Body)

	if _, err := r.Read(); err != nil { // ignore headers
		hqgolog.Fatal().Msg(err.Error())
	}

	schemes = make([]string, 0)

	for {
		record, err := r.Read()
		if err == io.EOF {
			break
		}

		if err != nil {
			hqgolog.Fatal().Msg(err.Error())
		}

		if strings.Contains(record[0], "OBSOLETE") {
			continue // skip obsolete schemes; note the scheme column is abused
		}

		schemes = append(schemes, record[0])
	}

	return
}

func writeSchemes(schemes []string, path string) (err error) {
	f, err := os.Create(path)
	if err != nil {
		return
	}

	defer f.Close()

	return schemesTmpl.Execute(f, struct {
		Schemes []string
	}{
		Schemes: schemes,
	})
}
